### PR TITLE
Add debian directory for debuild support

### PR DESCRIPTION
**Pull request by bb2k**

### CODE REVIEW

**Comment by morbidrsa** [comment]
Args, bad timing. If you're willing to maintain the debian packaging part, I'm fine with it. But can you please also post the series on the mailing list? Thanks

**Comment by cleech** [comment]
Shouldn't these patches be evaluated for merging not just dropped in a debian subdir?  And what's with the extra copy of the man pages?

**Comment by morbidrsa** [comment]
That's why I asked to send it to the mailing list, so we can actually evaluation all.

**Comment by bb2k** [comment]
OK, we found other problems and wish to propose a clean 1.0.29 package, i'll then close this pull request. We 'll prosose a patch to the list as soon as possible.

**Comment by morbidrsa** [comment]
@BB2K One thing to keep in mind though, currently the mailinglist is for subscribers only and I can't change that. As much as I whished

**Pull request closed without merging**
